In [1]:
# Calling NumPy library (with affection)
import numpy as np

In [2]:
myarray = np.array([1, 2, 3, 4, 5]) # creating an array with integer elements 1, 2, 3, 4, 5

In [3]:
# Printing the array as such to check
print(myarray)                     

[1 2 3 4 5]


In [4]:
# Checking the type of elements on the array just creaed above
print(type(myarray))

<class 'numpy.ndarray'>


In [5]:
# Checking the shape of the array, such as number of rows and cols
print(myarray.shape)

(5,)


In [6]:
# Zero dimension array
myarray = np.array(24)
print(myarray)
print(myarray.shape)

24
()


In [8]:
# Creating of 2D array
myarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(myarray) # Printing the array itself
print(myarray.shape) # Printing the size of row and col of the array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [11]:
# Advance instruction to creating an array
x = np.arange(0,10,1,dtype=float) # int, float, complex
print(x) # Print the array

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [12]:
# Another advance instruction to creating an array using linspace
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [26]:
# Arange, np.arange([start, ]stop, [step, ]dtype=None, *, like=None)
y1=np.arange(0, 5, 0.5, dtype=int)
y2=np.arange(-3, 3, 0.5, dtype=int)
print(y1)
print(y2)

[0 0 0 0 0 0 0 0 0 0]
[-3 -2 -1  0  1  2  3  4  5  6  7  8]


In [14]:
# Changing Shape
# Create 2x5 matrix first (2D array)
x = np.arange(10, dtype=int).reshape(2,5) # 2x5 matrix (row, col)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [15]:
# Flatten the array different shape, not to complete 1D
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Transpose
# Create 3x3 matrix first (2-D array)
x = np.arange(1,10,1).reshape(3,3)  # Reshape to 3x3 matrix
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
np.transpose(x) # Actual transpose of the matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [19]:
# Adding / Removing Elements (this is also part of resizing of array)
x = np.array([[1,2,3],[4,5,6]])
print(x)
print(x.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [20]:
# resize to new row and col
y = np.resize(x, (3,2))
print(y)
print(y.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [22]:
# Example of Append
x = np.array([[1,2,3],[4,5,6]])
# append three elements on axis=0
print(np.append(x, [[7,8,9]],axis=0))
# append three elements on axis=1
print(np.append(x,[[7,8,9],[10,11,12]],axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
